### ISSUE TITLE
Kapsig before first modelling

### ISSUE THREAD

**Issue by JanaKoehler1985** [mzechmeister/viper#32]
https://github.com/mzechmeister/viper/blob/f5424531dbf13c0d9502c00c47752ae8474d98a1/viper.py#L376-L387

I realized already a few times, that when using the telluric froward modeling, the `kapsig` function at this position of the script leads to worse results, compared to switching it off. I am thinking of whether removing it (as kapsig is also performed at a later stage) or changing it to the parameter  `prekapsig` so that the user can switch it off and still have the option of using `kapsig` after the first real modelling process.

**Comment by mzechmeister** [comment]
I would not switch it off.
`prekapsig` or maybe better `kapsigpre` or `kapsig0` is one idea.
Overloading `kapsig` is another idea; it could become a list  `-kapsig 0iter+ [1iter+] ...` .
(But alternatively, `-kapsig` arguments might be preserved for asymmetric clippping: `-kapsig <kaplower> <kapupper>` or even order specific kapsig values.)

(BTW, the parameter we enter is actually $\kappa$ and the process is called kappa-sigma clipping
$\kappa \cdot \sigma$ (sigma=std). Thus the option could be called `kap` or `kappa`, but `kapsig` is probably more catchy.)

Note there is also bug.
Bad `resid` are set to `0` (L381) instead of `nan`, thus biasing the `nanstd` (L383) towards zero.

**Comment by JanaKoehler1985** [comment]
I also think it is good to keep it. 

I am not sure if I like the list option or not. Would you have something like `-kapsig none 4.5` in mind, when switching of the "prekapsig"? Somehow I also don't like to come up with too much new parameters, but we should come along with something that is easy to understand for other users.

And you are right about the bug. Have to change it.

**Comment by mzechmeister** [comment]
Yes, skipping preclipping would then mean `-kapsig none 4.5`.
I think, it is also easy to understand. Of course it must be documented.

(Moreover, an idea to potentially handle asymmetric clipping at the same time:
 `-kapsig none -4:2.7`.)

**Comment by JanaKoehler1985** [comment]
I think I can live with `-kapsig none 4.5` (and the more I think about it, the more I like it). 

But I am not quite sure about the asymmetric clipping, even it would make sense. But I think it would be ok with me, if we do it in a way that `-kapsig none -4:2.7` and `-kapsig none 4.5` works as input.

**Comment by mzechmeister** [comment]
Asymmetric clipping was just an idea. We will not implement it.
serval also doesn't have it (only one of my spectrum extraction routines).

**Comment by JanaKoehler1985** [comment]
Just one question. While testing I realized that `none` as input doesn't work because of type=float. Ok, I could use a high value for the first input, that should work fine.

And I think I would prefer it that the user can write  `-kapsig 3.5 4.5` or `-kapsig 4.5` (in second case 4.5 would be used for both kapsig)

**Comment by mzechmeister** [comment]
Then we have to omit or rework the type checking...

Or, I think, `kapsig=0` (actually inf), is easiest here.

> `-kapsig 4.5` (in second case 4.5 would be used for both kapsig)

Yes. That was my intention as well.

**Comment by JanaKoehler1985** [comment]
Indeed, `kapsig=0` is an option that would work.

**Comment by mzechmeister** [comment]
I think we are done.
