### ISSUE TITLE
vpr.py: STRING operator applied to undefined or non-STRING variable

### ISSUE THREAD

**Issue by JanaKoehler1985** [mzechmeister/viper#34]
While working on the vpr GUI and testing your newest updates, I run into an error.
When running for example: `python3 vpr.py tmp.rvo.dat` I got the following error:

vpr.py:104: RuntimeWarning: invalid value encountered in true_divide
  self.e_RV = np.std(self.rv, axis=0) / (len(self.onames)-1)**0.5
Number of chunks: 1
rms(RV) [m/s]:      45.39829311381922
median(e_RV) [m/s]: nan
pause vpr.py line 137:  RV time serie
Use '()[]^$' in gnuplot window to go through epochs n. Press Enter in terminal to quit.
pause vpr.py line 177:  rv order dispersion
         line 118: internal error : STRING operator applied to undefined or non-STRING variable

Get the same when using f.e. `python3 vpr.py tmp.rvo.dat -oset 7`.

**Comment by mzechmeister** [comment]
I remember that I have seen the issue before; but then it was gone.
It was because I used gnuplot v5.2, but then I switched to another computer with gnuplot v5.4, where the problem disappeared.

It was because of this construct
```
"" us 1:2:(spectrum=strcol(4), $3) ... title spectrum." RV_{".n."}"
```
which shall bring the spectrum name to the legend. But it seems gnuplot v5.2 parses the title first.
I worked it around by defining `spectrum="",` in the plot commands.

Thus the spectrum name is only shown in the legend with v5.4, but not with v5.2.
In any case, the spectrum name will be printed to the terminal.


I also wrote a string `replace` function. The filenames can have underscores, which would lead subscripts in `enhanced` mode (only desired for `RV_n`).
