### ISSUE TITLE
Bug: Plot res by using GUI_vpr.py

### ISSUE THREAD

**Issue by JanaKoehler1985** [mzechmeister/viper#35]
When calling `-res` via the GUI the plot closes immediately due to (even before my latest update):

https://github.com/mzechmeister/viper/blob/38e28c7cf6a283f6b16032ad9cf6184310b196f7/vpr.py#L229-L231

I already realized before that pause and exit() doesn't work together. Can it be fixed in `vpr.py` or do we need another way of calling the function in `GUI_vpr.py`?

**Comment by mzechmeister** [comment]
`pause` is not affected by `exit`.

I got similar issues. I found the plot closes, because  python gets an error.
```
  File "vpr.py", line 211, in plot_res
    pause('residuals stacked: o=%s' % o)
TypeError: not all arguments converted during string formatting
```
`o` was an tuple longer than one `(7,8)`; thus python failed before entering `pause` or `exit`.
Formatting would only work if `o` is a scalar or a list. But `np.s_[7,8]` returns `(7, 8)`. Only `np.s_[[7,8]]` returns `[7, 8]`.

Anyway, more than one orders, i.e. list of orders, likely was not considered when it was implemented.
Also `nset` needs to be specified. It only worked like this: `vpr <tag> -res -oset 7 -nset 5,6,7`.

So while functional, some cases need to be catched.

**Comment by JanaKoehler1985** [comment]
Well, that is another error than the one I am talking about. If you choose just a single value for `nset` and `oset` (in the GUI), you get no error but the plot closes  immediately. Just try f.e. `nset` 5 and `oset` 7 in the GUI. When removing the exit(), the plot is shown, but than the script is not ended and therefor causes another error.

**Comment by mzechmeister** [comment]
I see; was easy to fix.
